save_path: /home/${oc.env:USER}/data/failgen_data
obs_mode: rgb
render_mode: sensors
shader: default
sim_backend: auto
image_size: [256, 256]
stages: [0, 1, 2, 3]
failures:
  - type: grasp
    enabled: false
    stages: [2]
  - type: trans_x
    enabled: false
    stages: [0, 1, 3]
    range: 0.1
  - type: trans_y
    enabled: false
    stages: [0, 1, 3]
    range: 0.1
  - type: trans_z
    enabled: false
    stages: [0, 1, 3]
    range: 0.1
#  - type: rot_x
#    enabled: false
#    stages: [0, 1, 3]
#    range: 0.01
#  - type: rot_y
#    enabled: false
#    stages: [0, 1, 3]
#    range: 0.01
#  - type: rot_z
#    enabled: false
#    stages: [0, 1, 3]
#    range: 0.01